export const publishers = [
  'Angel',
  'Archangel',
  'Marvel Comics',
  'DC Comics',
  'NBC - Heroes',
  'Sharon Carter',
  'Wildstorm',
  'Dark Horse Comics',
  'Tempest',
  'Image Comics',
  'Giant-Man',
  'Toxin',
  'Speedy',
  'Oracle',
  'Hawkfire',
  'Misfit',
  'Nightwing',
  'Icon Comics',
  'Universal Studios',
  'George Lucas',
  'Star Trek',
].sort()
